name: Build Windows wheel (Py 3.12)

on: [push, pull_request]

jobs:
  wheel-win64-py312:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12 (x64)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools wheel

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: affinegap-win64-py312
          path: dist/*.whl
